#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 300
      min-spare: 50
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jtsys?serverTimezone=GMT%2B8&characterEncoding=UTF8
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true
      exclude: /templates/**
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    cache: false
mybatis:
  configuration:
    default-statement-timeout: 60
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.zl.dongba: warn
